version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - "8000:8000"
    volumes:
      - ./skyeye-restful-server:/skyeye-docker-server
      - ./nginx:/etc/nginx/conf.d
      - ./skyeye-restful-server/static:/static
      - ./skyeye-restful-server/media:/media
    depends_on:
      - web
  web:
    build:
      context: ./skyeye-restful-server
      dockerfile: Dockerfile
    # command: gunicorn server.wsgi:application --bind 0.0.0.0:8000
    command: daphne -b 0.0.0.0 -p 8000 server.asgi:application
    volumes:
      - ./skyeye-restful-server:/skyeye-docker-server
      - ./skyeye-restful-server/static:/static
      - ./skyeye-restful-server/media:/media
    ports:
      - "8000"