# Generated by Django 4.1.5 on 2023-01-27 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('helikite', '0001_initial'),
        ('winch', '0001_initial'),
        ('mission_device', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('site_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('installation_date', models.DateField(blank=True, null=True)),
                ('helikite_serial_number', models.OneToOneField(blank=True, db_column='helikite_serial_number', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='helikite.helikite')),
                ('missiondevice_serial_number', models.OneToOneField(blank=True, db_column='missiondevice_serial_number', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mission_device.missiondevice')),
                ('winch_serial_number', models.OneToOneField(blank=True, db_column='winch_serial_number', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='winch.winch')),
            ],
        ),
    ]
