# Generated by Django 4.1.5 on 2023-02-01 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skyeye', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='site',
            options={'managed': False},
        ),
    ]
