# Generated by Django 4.2a1 on 2023-02-13 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skyeye', '0002_alter_site_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='site',
            table='site',
        ),
    ]
