# Generated by Django 4.2a1 on 2023-03-10 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skyeye', '0003_alter_site_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettingsConfig',
            fields=[
                ('site', models.OneToOneField(help_text='Site ID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='skyeye.site')),
                ('missiondevice_altitude_high', models.FloatField(blank=True, help_text='임무장치 고도 상한', null=True)),
                ('missiondevice_altitude_low', models.FloatField(blank=True, help_text='임무장치 고도 하한', null=True)),
                ('missiondevice_voltage_high', models.FloatField(blank=True, help_text='임무장치 전압 상한', null=True)),
                ('missiondevice_voltage_low', models.FloatField(blank=True, help_text='임무장치 전압 하한', null=True)),
                ('winch_tetherline_length_high', models.FloatField(blank=True, help_text='윈치 티더선 길이 상한', null=True)),
                ('winch_tetherline_length_low', models.FloatField(blank=True, help_text='윈치 티더선 길이 하한', null=True)),
                ('winch_tetherline_angle_high', models.FloatField(blank=True, help_text='윈치 티더선 각도 상한', null=True)),
                ('winch_tetherline_angle_low', models.FloatField(blank=True, help_text='윈치 티더선 각도 하한', null=True)),
                ('winch_tetherline_tension_high', models.FloatField(blank=True, help_text='윈치 티더선 장력 상한', null=True)),
                ('winch_tetherline_tension_low', models.FloatField(blank=True, help_text='윈치 티더선 장력 하한', null=True)),
                ('winch_wind_speed_high', models.FloatField(blank=True, help_text='풍속 상한', null=True)),
                ('winch_wind_speed_low', models.FloatField(blank=True, help_text='풍속 하한', null=True)),
            ],
            options={
                'db_table': 'site_settings_config',
                'managed': False,
            },
        ),
    ]
