# Generated by Django 4.1.5 on 2023-01-26 05:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fire_detection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detection',
            name='ai_model',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='detection',
            name='class_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='detection',
            name='date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='detection',
            name='detection_rate',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='detection',
            name='image',
            field=models.ImageField(null=True, upload_to='%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='detection',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
