# Generated by Django 4.1.5 on 2023-01-27 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Helikite',
            fields=[
                ('serial_number', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('cubic', models.IntegerField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('payload', models.FloatField(blank=True, null=True)),
                ('production_year', models.TextField(blank=True, null=True)),
                ('image_file_path', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'helikite',
                'managed': False,
            },
        ),
    ]
