# Generated by Django 3.2.14 on 2023-01-04 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('serial_number', models.CharField(help_text='카메라 일련번호', max_length=100, primary_key=True, serialize=False)),
                ('maximum_angle_roll', models.IntegerField(blank=True, help_text='Roll 최대각', null=True)),
                ('minimum_angle_roll', models.IntegerField(blank=True, help_text='Roll 최소각', null=True)),
                ('maximum_angle_pitch', models.IntegerField(blank=True, help_text='Pitch 최대각', null=True)),
                ('minimum_angle_pitch', models.IntegerField(blank=True, help_text='Pitch 최소각', null=True)),
                ('maximum_angle_yaw', models.IntegerField(blank=True, help_text='Yaw 최대각', null=True)),
                ('minimum_angle_yaw', models.IntegerField(blank=True, help_text='Yaw 최소각', null=True)),
                ('zoom_magnification', models.IntegerField(blank=True, help_text='무게', null=True)),
                ('night_vision', models.IntegerField(blank=True, help_text='나이트 비전 가능 여부', null=True)),
                ('protocol', models.IntegerField(blank=True, help_text='프로토콜 타입', null=True)),
            ],
            options={
                'db_table': 'camera',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Missiondevice',
            fields=[
                ('serial_number', models.CharField(help_text='임무장치 일련번호', max_length=100, primary_key=True, serialize=False)),
                ('primary_sensor', models.CharField(blank=True, help_text='기본 센서', max_length=100, null=True)),
                ('extended_sensor', models.CharField(blank=True, help_text='확장 센서', max_length=100, null=True)),
                ('communication_type', models.CharField(blank=True, help_text='통신방식', max_length=100, null=True)),
                ('mobile_service_company', models.CharField(blank=True, help_text='통신사', max_length=100, null=True)),
                ('weight', models.FloatField(blank=True, help_text='무게', null=True)),
                ('production_year', models.TextField(blank=True, help_text='제작 년도(1901-2155)', null=True)),
            ],
            options={
                'db_table': 'missiondevice',
                'managed': False,
            },
        ),
    ]
