# Generated by Django 4.2a1 on 2023-02-14 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_eventstream', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventCounter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('value', models.BigIntegerField(default=0)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(db_index=True, max_length=255)),
                ('type', models.CharField(db_index=True, max_length=255)),
                ('data', models.TextField()),
                ('eid', models.BigIntegerField(db_index=True, default=0)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'unique_together': {('channel', 'eid')},
            },
        ),
    ]
